### ISSUE TITLE
the image sizes are too small 

### ISSUE THREAD

**Issue by kpopdev** [KPOPCORD/blackpink#1]
hi good job and great work im really happy that u made this.

the images are too small when im using feeds 
https://v-phinf.pstatic.net/20210710_169/1625896473240JxhHb_JPEG/image.JPEG?type=f144x144

its all bc of the type=f144x144

most of feeds are like this. also bc of this it wont show the images too.

**Comment by SOLPLPARTY** [comment]
It's not that I don't know it. Unable to fix. This is a roundabout way to get it. Gets the image value as is. It's not a service I made. 

It was separately hosted to use the GitHub action. If overloaded, they'll stop it on the platform side. 

Already they have blocked the other way. It's the way I'm left now. Anyway, the discode provides previews anyway. The same goes for Twitter.
